Customer endpoints to create a new customer, get a customer, update a customer and delete a customer
gcostacoelho/AlfarBackendChallenge_CSharp pull request #4
Opened 2023-11-16 13:45 UTC by gcostacoelho

2023-11-16 14:00 UTC, jordhanfelix requested changes
Reveja as alterações propostas

2023-11-17 15:25 UTC, gcostacoelho commented on src/Controllers/CustomerController.cs
> +        [ProducesResponseType(StatusCodes.Status204NoContent)]
Pra mim não faz sentido retornar um 200, sendo que o que o usuário solicitou não existe no BD

2023-11-17 15:33 UTC, gcostacoelho commented on src/Controllers/CustomerController.cs
> +        [ProducesResponseType(StatusCodes.Status204NoContent)]
Pra mim não faz sentido retornar um 200, sendo que o que o usuário solicitou não existe no BD... Talvez um 404 caberia aqui?

2023-11-17 15:34 UTC, gcostacoelho commented on src/Services/CustomerService/CustomerService.cs
> +        public async Task<Customer> PostNewCustomer(Customer customer)
Criei um middleware de erro para lidar com possíveis erros que possam dar ao salvar o customer no banco de dados

2023-11-17 15:35 UTC, gcostacoelho commented on src/Controllers/CustomerController.cs
> +            return response;
Não sei se entendi muito bem a questão, mas substitui o `return responsel;` por um `return Ok(response);`

2023-11-17 19:46 UTC, jordhanfelix requested changes
Tente rever alguns retornos que possui em seu controller, as anotações de respostas devolvidas, os tipos de respostas e etc..

2023-11-17 19:46 UTC, jordhanfelix commented on src/Controllers/CustomerController.cs
> +        [ProducesResponseType(StatusCodes.Status204NoContent)]
Eu havia escrito um texto bonitinho, ai joguei ele no chatgpt e deixei ele concluir o raciocinio: 

A ideia de retornar "no content" para situações em que um recurso não é encontrado pode parecer intuitiva à primeira vista, mas na prática, essa abordagem pode causar problemas significativos no consumo de uma API. Imagine que você está interagindo com uma API e, ao solicitar informações, a resposta que você recebe é "NO CONTENT". Embora a API interprete códigos de erro entre 400 e 500 como aceitáveis, seu código pode quebrar quando precisa dos dados efetivos.

Essa abordagem pode parecer trivial, mas há uma razão importante para evitar o uso indiscriminado de "no content". Os códigos de status 200, 201, 202 e assim por diante indicam que a requisição foi processada com sucesso. Ao usar "no content" para indicar que um recurso não foi encontrado, você está, de certa forma, enviando uma mensagem contraditória. O código sugere que tudo ocorreu conforme o esperado, enquanto o comportamento desejado seria o retorno de um objeto representando a ausência do recurso.

Em resumo, escolher códigos de status apropriados é crucial para garantir uma comunicação clara entre as partes envolvidas. O uso de "no content" para representar a ausência de um recurso pode levar a interpretações equivocadas e resultar em comportamentos inesperados no lado do consumidor da API. Portanto, é recomendável utilizar códigos de status que reflitam com precisão a natureza da resposta, contribuindo para uma interação mais consistente e compreensível entre os sistemas.

2023-11-17 19:46 UTC, jordhanfelix commented on src/Controllers/CustomerController.cs
> +        [ProducesResponseType(StatusCodes.Status204NoContent)]
não reflete o tipo de resposta que você devolve para o usuário.

2023-11-17 19:46 UTC, jordhanfelix commented on src/Controllers/CustomerController.cs
> +        [ProducesResponseType(StatusCodes.Status204NoContent)]
Eu havia escrito um texto bonitinho, ai joguei ele no chatgpt e deixei ele concluir o raciocinio:

A ideia de retornar "no content" para situações em que um recurso não é encontrado pode parecer intuitiva à primeira vista, mas na prática, essa abordagem pode causar problemas significativos no consumo de uma API. Imagine que você está interagindo com uma API e, ao solicitar informações, a resposta que você recebe é "NO CONTENT". Embora a API interprete códigos de erro entre 400 e 500 como aceitáveis, seu código pode quebrar quando precisa dos dados efetivos.

Essa abordagem pode parecer trivial, mas há uma razão importante para evitar o uso indiscriminado de "no content". Os códigos de status 200, 201, 202 e assim por diante indicam que a requisição foi processada com sucesso. Ao usar "no content" para indicar que um recurso não foi encontrado, você está, de certa forma, enviando uma mensagem contraditória. O código sugere que tudo ocorreu conforme o esperado, enquanto o comportamento desejado seria o retorno de um objeto representando a ausência do recurso.

Em resumo, escolher códigos de status apropriados é crucial para garantir uma comunicação clara entre as partes envolvidas. O uso de "no content" para representar a ausência de um recurso pode levar a interpretações equivocadas e resultar em comportamentos inesperados no lado do consumidor da API. Portanto, é recomendável utilizar códigos de status que reflitam com precisão a natureza da resposta, contribuindo para uma interação mais consistente e compreensível entre os sistemas.

2023-11-17 19:46 UTC, jordhanfelix commented on src/Services/CustomerService/CustomerService.cs
> +        public async Task<Customer> PostNewCustomer(Customer customer)
ficou bom o middleware.

2023-11-18 17:15 UTC, gcostacoelho commented on src/Controllers/CustomerController.cs
> +        [ProducesResponseType(StatusCodes.Status204NoContent)]
Atualizado para retornar o status 404, caso não encontre o customer

2023-11-18 17:16 UTC, gcostacoelho commented on src/Controllers/CustomerController.cs
> +        [ProducesResponseType(StatusCodes.Status204NoContent)]
Atualizado para retornar o status 404, caso não encontre o customer

2023-11-18 17:33 UTC, gcostacoelho commented on src/Controllers/CustomerController.cs
> +        [ProducesResponseType(StatusCodes.Status204NoContent)]
Altereado para o HTTP 200, como alinhado na call, tendo em vista que estou fazendo um delete físico

2023-11-18 17:55 UTC, jordhanfelix commented on src/Controllers/CustomerController.cs
> +            return response;
era isso mesmo.

2023-11-18 17:55 UTC, jordhanfelix commented on src/Controllers/CustomerController.cs
> +        [ProducesResponseType(StatusCodes.Status204NoContent)]
top

2023-11-18 17:55 UTC, jordhanfelix commented on src/Controllers/CustomerController.cs
> +        [ProducesResponseType(StatusCodes.Status204NoContent)]
top

2023-11-18 17:56 UTC, jordhanfelix approved these changes

2023-11-18 18:00 UTC, tonikopimenta approved these changes

2023-11-18 18:01 UTC, merged